### ISSUE TITLE
Deleting entities.

### ISSUE THREAD

**Issue by lghamie** [oVirt/ovirt-ansible#114]
Hi, I have a question that might become a suggestion.

Why do you use "state: absent" for deleting entities? I think it would be better if I could just provide a full list of the entities that I want, and the ones that are created on ovirt but are not present on my list get deleted.

What do you think?

**Comment by machacekondra** [comment]
Hi,

well, it would be quite complicated to implement it, but doable. We can add an attribute like `strict` or similar. And remove all entities which aren't listed. But it would be very complicated.

What is your exact use case?

Thanks.

cc @mwperina

**Comment by lghamie** [comment]
First of all, thanks for answering so fast and for your interest.

In my use case, I have a database with all the VMs, networks, and NICs, and I use it for provisioning an underlying ovirt installation, this VMs are dynamic, I might create or delete some at any time. I use a dynamic inventory, which reads from my database and uses an ansible playbook that uses some "with items" clauses to create all the ovirt-ansible antities (vm, nics, networks). This currently works fine for creating items, but I've found that it's not very straightforward the path for deleting.

Since I only want to update my database, when I delete a VM I just want to delete it from the database. So that when I run the playbook again, the VMs that are not in the new output of the inventory will get deleted, which would be pretty transparent for us.

**Comment by machacekondra** [comment]
Ok, I understand your use case. What you can do to workaround that is create a following post-tasks in your playbook:

```yaml
 - hosts: xyz

   vms:
     - name: vm1
     - name: vm2 

   roles:
     - ovirt-vm-infra

   post_tasks:
     - name: Get VMs to remove
       ovirt_vms_facts:
         auth: "{{ ovirt_auth }}"
         pattern: "{{ vms | map(attribute='name') | map('regex_replace', '(.*)', 'name!=\\1') | list | join(' and ') }}"

     - name: Remove unwanted VMs
       ovirt_vms:
         auth: "{{ ovirt_auth }}"
         state: absent
         name: "{{ item }}"
       with_items: "{{ ovirt_vms }}"
```

It will just find all VMs which aren't in `vms` variable in oVirt and remove them. Is this something you look for?
