### ISSUE TITLE
ovirt-cluster-upgrade: Add option to perform full host upgrade

### ISSUE THREAD

**Issue by djasa** [oVirt/ovirt-ansible#137]
Hi,

Given the complexity of doing the update process cleanly, it would be nice to be able to specify:
- upgrade all packages
- reboot
- set longer default timeout (may be useful for hosts with longer POST times)

First should be sufficient with e.g.
```
- name: upgrade all packages
  package: all
    state: latest
  when: upgrade_all == True
```

Reboot needs command with a little delay to allow ansible logging out from ssh:
```
- name: reboot host
  command: shutdown -r +5
  when: reboot_host == True
```

Reboot interval would probably require a new option and use of wait_for module. (Writing based on docs, I didn't try this myself. This code should wait for 30 s idle, then check host's VDSM port every 5 seconds and continue once vdsm starts listening or give up after 10 minutes):
```
- name: wait before host comes back online
  wait_for:
    host: "{{ item.name }}"
    port: 54321
    state: started
    delay: 30
    sleep: 5
    timeout: "{{ reboot_timeout | default 600 }}"
```
