### ISSUE TITLE
Move network roles in clusters to ovirt_clusters module?

### ISSUE THREAD

**Issue by djasa** [oVirt/ovirt-ansible#142]
Hi,

when typing my existing RHV setup to ansible, I was wondering why are cluster network roles specified at each network instead of at cluster. The main disadvantages are IMO:
* much more typing. E.g. you have to specify `display: false` for each network instead of having single `display: NETWORK_NAME` statement given at cluster
* vulnerability to errors for no gain: with per-cluster `display: NETWORK_NAME`, you can validate that just one network is specified as display right in the ansible module (the same is true for migration network)

I don't have a strong opinion for VM networks and required networks specification where the inherent validation and less typing are not really applicable (it doesn't matter that much if you specify per-network boolean or per-cluster list in this case).

The only downside I can think of is need to have cluster set up split to two tasks but that's IMO an acceptable cost, see example below:
```yaml
- name: set up clusters
  ovirt_clusters:
    # everything but networks

- name: set up networks
  ovirt_networks:
    # now set up networks

- name: set up cluster network roles
  ovirt_clusters:
    name: cluster_name
    display_network: my_display_network
    migration_network: my_mgmt_network
    # These are of no real benefit IMO so just for consistency sake...
    required_networks:
    - my_mgmt_network
    - my_display_network
    - infra_servers
    - prod_servers
    vm_networks:
    - infra_servers
    - web_servers
    - playground
```
