### ISSUE TITLE
ovirt-aaa-jdbc: allow setting attributes via this role 

### ISSUE THREAD

**Issue by tareqalayan** [oVirt/ovirt-ansible#48]
@mwperina 
@machacekondra 

I would like to have the ability to set some attributes from: 
--attribute=[<name>=<value>]
    Available names:
      department
      description
      displayName
      email
      firstName
      lastName
      title

the command should be something like 
"/usr/bin/ovirt-aaa-jdbc-tool user {{ (item.state is undefined or item.state == 'present') | ternary('add','delete') }} {{ item.name }} --attribute=firstName={{ item.name }} --attribute=department='My department'"

I am thinking to add an extra_ops parameter:
    users:
     - name: user1
       authz_name: internal-authz
       password: 1234568
       valid_to: "2018-01-01 00:00:00Z"
       extra_ops: --attribute=firstName=bob --attribute=department='My department'"
     - name: user2
       authz_name: internal-authz
       password: 1234568
       valid_to: "2018-01-01 00:00:00Z"

would this be fine by you?
or do you have another suggestion?

**Comment by machacekondra** [comment]
why not just have `attributes` dicitnary?

```yaml
users:
     - name: user1
       authz_name: internal-authz
       password: 1234568
       valid_to: "2018-01-01 00:00:00Z"
       attributes:
         firstname: 'bob'
         department: 'My department'
```
